version: "3"
services:
    vite:
        build: .
        ports:
            - "5173:5173"
        volumes:
            - .:/app
            - node_modules:/app/node_modules # named volumeを使用
        environment:
            - HOST=0.0.0.0 # Viteが外部アクセス受け入れるため
            - CHOKIDAR_USEPOLLING=true

volumes:
    node_modules:
