version: "3"
services:
    vite-prod:
        build:
            context: .
            dockerfile: Dockerfile.prod
        ports:
            - "80:80"
        restart: unless-stopped
        environment:
            - NODE_ENV=production
